### ISSUE TITLE
Hi there, I'm having problems when I try to install this plugin.

### ISSUE THREAD

**Issue by ugcoder** [KSXGitHub/circular-widgets-gnome-45#1]
When I try to install it, I get the following error and I don't know how to fix it.
=========================================================================================================
Progress: resolved 46, reused 0, downloaded 0, added 0
 CERT_HAS_EXPIRED  request to https://registry.npm.taobao.org/@girs/gio-2.0/-/gio-2.0-2.78.0-3.2.7.tgz failed, reason: certificate has expired

FetchError: request to https://registry.npm.taobao.org/@girs/gio-2.0/-/gio-2.0-2.78.0-3.2.7.tgz failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/usr/lib/node_modules/pnpm/dist/pnpm.cjs:75683:18)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:492:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Progress: resolved 46, reused 0, downloaded 0, added 0
make: *** [Makefile:19: deps] Error 1

=========================================================================================================
Can you help fix this bug?

**Comment by ugcoder** [comment]
OS: Arch Linux
Kernel: 6.7.5
DE: Gnome 45.4

**Comment by KSXGitHub** [comment]
It probably because the npm registry you use has outdated certificate. Can you try the official npm registry (`https://registry.pnpmjs.com`)?

**Comment by KSXGitHub** [comment]
If you still cannot build it, then you may temporary use this pre-built archive: [gnome-extension-circular-widgets.zip](https://github.com/KSXGitHub/circular-widgets-gnome-45/files/14395527/gnome-extension-circular-widgets.zip)

Once I have completed porting all the extensions that I require, I will probably distribute them either via my custom pacman repository, or GitHub release, or the GNOME extension store. I haven't decided it yet.

**Comment by ugcoder** [comment]
> If you still cannot build it, then you may temporary use this pre-built archive: [gnome-extension-circular-widgets.zip](https://github.com/KSXGitHub/circular-widgets-gnome-45/files/14395527/gnome-extension-circular-widgets.zip)
> 
> Once I have completed porting all the extensions that I require, I will probably distribute them either via my custom pacman repository, or GitHub release, or the GNOME extension store. I haven't decided it yet.

Thank you for your response, I am following.
